github:
  client:
    id: f7425bc7ee111e40a70a5cf425be9d32eb47dcbe25b5b9617ef3229fa32984e1
    secret: 254b4670904f35567bb4daf0bf8268d92fc698f6f62a396aeb5b6b432319caf4
  redirect:
    uri: http://localhost:8081/callback
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: 8.141.64.248
    port: 6380
    database: 10

# 配置驼峰命名的映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出sql语句

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tNDAwGq6piZJ7T7GDRD
    accessKeySecret: JAER7sZQbpHX10lrJWdDcbsOEzIdCu
    bucketName: thiscommunity
logging:
  file:
    name: logs/community.log

  level:
    com:
      xzcube:
        community:
          mapper: debug
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 15
server:
  port: 8081
